x-local: &local
  restart: unless-stopped
  env_file: .env
  environment:
    PYTHONUNBUFFERED: 1
    PYTHONDONTWRITEBYTECODE: 1
  links:
    - database
  depends_on:
    database:
      condition: service_healthy
#    migrations:
#      condition: service_completed_successfully


services:

  api:
    <<: *local
    container_name: mirea-hahaton-api
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"

  query:
    <<: *local
    container_name: mirea-hahaton-query
    build:
      context: .
      dockerfile: ./query/Dockerfile

  database:
    container_name: mirea-hahaton-database
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    volumes:
      - mirea-hahaton-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"

  nats:
    container_name: mirea-hahaton-nats
    image: nats:2.10-alpine
    restart: unless-stopped
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - mirea-hahaton-volume:/data
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    command: -c /etc/nats/nats.conf


volumes:
  mirea-hahaton-volume: