x-local: &local
  restart: unless-stopped
  build:
    context: .
    dockerfile: Dockerfile
  env_file: .env
  environment:
    PYTHONUNBUFFERED: 1
    PYTHONDONTWRITEBYTECODE: 1
  links:
    - database
    - nats
  depends_on:
    database:
      condition: service_healthy
    nats:
      condition: service_healthy
    migrations:
      condition: service_completed_successfully


services:

  api:
    <<: *local
    container_name: mirea-hahaton-api
    volumes:
      - mirea-hahaton-volume:/app/static/xml
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: python -m app

  query:
    <<: *local
    container_name: mirea-hahaton-query
    volumes:
      - mirea-hahaton-volume:/app/static/xml
    command: python -m query

  scheduler:
    <<: *local
    container_name: mirea-hahaton-scheduler
    command: python -m scheduler

  migrations:
    <<: *local
    container_name: mirea-hahaton-migrations
    restart: no
    depends_on:
      database:
        condition: service_healthy
    command: alembic upgrade head

  database:
    container_name: mirea-hahaton-database
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    volumes:
      - mirea-hahaton-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 15s
      timeout: 4s
      retries: 3
      start_period: 3s

  nats:
    container_name: mirea-hahaton-nats
    image: nats:2.10-alpine
    restart: unless-stopped
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - mirea-hahaton-volume:/data
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      interval: 15s
      timeout: 4s
      retries: 3
      start_period: 3s
    command: -c /etc/nats/nats.conf -m 8222


volumes:
  mirea-hahaton-volume: