"""vuls

Revision ID: 0002
Revises: 0001
Create Date: 2024-11-23 15:27:10.792805

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.String(length=1024), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("vendor", sa.String(length=1024), nullable=False),
        sa.Column("soft_name", sa.String(length=1024), nullable=False),
        sa.Column("version", sa.String(length=1024), nullable=False),
        sa.Column("type", sa.String(length=1024), nullable=False),
        sa.Column("os", sa.String(length=1024), nullable=False),
        sa.Column("class_", sa.String(length=1024), nullable=False),
        sa.Column("date", sa.String(length=1024), nullable=False),
        sa.Column("cvss2", sa.String(length=1024), nullable=False),
        sa.Column("cvss3", sa.String(length=1024), nullable=False),
        sa.Column("danger_level", sa.String(length=1024), nullable=False),
        sa.Column("elimination_methods", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=1024), nullable=False),
        sa.Column("is_exploitation", sa.String(length=1024), nullable=False),
        sa.Column("elimination_info", sa.String(length=1024), nullable=False),
        sa.Column("urls", sa.String(length=1024), nullable=False),
        sa.Column("other_id", sa.String(length=1024), nullable=False),
        sa.Column("other_info", sa.String(length=1024), nullable=False),
        sa.Column("realtions", sa.String(length=1024), nullable=False),
        sa.Column("method_exploitation", sa.String(length=1024), nullable=False),
        sa.Column("method_fix", sa.String(length=1024), nullable=False),
        sa.Column("cwe_description", sa.String(length=1024), nullable=False),
        sa.Column("cwe_type", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vulnerabilities")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vulnerabilities")
    # ### end Alembic commands ###
