"""nullable_true

Revision ID: 0005
Revises: 0004
Create Date: 2024-11-23 19:38:26.491071

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "open_ports",
        "service",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.alter_column(
        "open_ports",
        "version",
        existing_type=sa.VARCHAR(length=128),
        nullable=True,
    )
    op.drop_column("open_ports", "protocol")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "open_ports",
        sa.Column(
            "protocol",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "open_ports",
        "version",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
    )
    op.alter_column(
        "open_ports",
        "service",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    # ### end Alembic commands ###
